### ISSUE TITLE
I work it  but  IRC not show

### ISSUE THREAD

**Issue by zhaoyujia11808** [TivonJJ/html5-music-player#1]
I work it  but  IRC not show

**Comment by TivonJJ** [comment]
What is your browser and device

**Comment by zhaoyujia11808** [comment]
chrome

**Comment by zhaoyujia11808** [comment]
window  chrome

**Comment by zhaoyujia11808** [comment]
music  work   but the  irc not  work

**Comment by TivonJJ** [comment]
You need to open the debug tool and toggle on the device mode，Then  the browser has touch events, The demo app has three split panel。you can swipe to right or left. 
panel 1: music list;
panel 2: LRC panel;
panel 3: Album information

**Comment by zhaoyujia11808** [comment]
![image](https://cloud.githubusercontent.com/assets/2081162/7037317/4f0167b0-ddd3-11e4-84fd-73d942c180f7.png)

**Comment by TivonJJ** [comment]
利用鼠标向左滑页

**Comment by TivonJJ** [comment]
就像手机APP一样，向左拖动，这个应用本来是在手机上运行的，所以使用的touch事件，且按照手机应用风格和操作习惯设计

**Comment by zhaoyujia11808** [comment]
谢谢  非常不错 我想看看把卡拉ok集成字幕
